replicaCount: 2

image:
  repository: kubevamshi/vamika-frontend
   tag: "v1.0.0-2025-02-22-202030"
  pullPolicy: Always

resources:
  requests:
    memory: 100Mi
    cpu: 100m
  limits:
    cpu: 150m
    memory: 150Mi
securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 999
createNamespace: true
