apiVersionapiVersion: apps/v1
kind: Deployment
metadata:
  name: vm-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vm-frontend
  template:
    metadata:
      labels:
        app: vm-frontend
    spec:
      containers:
        - name: vm-frontend
          image: "{{ secrets.IMAGE_REGISTRY  }}/v{{ Values.image }}:{{ (.Values.image).tag | default "0.0.1" }}"
          ports:
            - containerPort: 3000
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | trim | nindent 12 }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | trim | nindent 12 }}
          {{- end }}
