apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-virtualservice
  namespace: frontend
spec:
  hosts:
    - frontend.example.com
  gateways:
    - frontend-gateway
  http:
    - route:
        - destination:
            host: frontend-service
            port:
              number: 3000