apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-virtualservice
  namespace: frontend
spec:
  hosts:
    - frontend.example.com
  gateways:
    - frontend-gateway
  http:
    - match:
        - uri:
            prefix: /api/
      route:
        - destination:
            host: backend-service.backend.svc.cluster.local
            port:
              number: 8080
    - route:
        - destination:
            host: frontend-service
            port:
              number: 3000
    