name: VM-FRONTEND

on: 
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        env:
            IMG_NAME:
            BUILDER_IMAGE:
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-versions: '20.x'
            - name: Install Dependencies
              working-directory: .
              run: npm ci
            - name: Run Unit Tests
              run: npm run test



  
 


