name: CI/CD with Automated Testing

on:
  push:
    branches:
      - dev-1
  pull_request:
    branches:
      - dev-1

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js (or your preferred runtime)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Run Unit Tests
      - name: Run Unit Tests
        run: npm run test
        continue-on-error: false # Fail the pipeline if tests fail

      # Step 5: Generate Test Reports
      - name: Generate Test Reports
        if: always() # Always run this step, even if tests fail
        run: |
          mkdir -p test-reports
          jest --json --outputFile=test-reports/test-report.json
          jest --reporters=jest-junit
          jest --reporters=jest-html-reporter

      # # Step 6: Upload Test Reports
      # - name: Upload Test Reports
      #   if: always() # Always run this step, even if tests fail
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: test-reports
      #     path: test-reports/
